version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: project_pulse_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_pulse
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit
    container_name: project_pulse_mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
